name: Node.js CI

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: yarn install

    - name: Install Foundry and Anvil
      run: |
        curl -L https://foundry.paradigm.xyz | bash
        source ~/.bashrc
        foundryup

    - name: Build
      run: yarn build

    - name: Test
      run: yarn test
